kotlin.code.style=official
archives_base_name=datapacktools
maven_group=com.pulse
loom_version=1.10-SNAPSHOT
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.9
fabric_kotlin_version=1.13.6+kotlin.2.2.20
fabric_api_version=0.90.0+1.20.1
mod_version=1.0.0

org.gradle.jvmargs=-Xmx4000m