package com.pulse.datapacktools.main.packets.custom

import com.pulse.datapacktools.main.config.ModConfig
import com.pulse.datapacktools.main.utils.DatapacksUtils.createDefaultDatapack
import com.pulse.datapacktools.main.utils.DatapacksUtils.updateDatapack
import com.pulse.datapacktools.main.utils.SessionUtils
import com.pulse.datapacktools.packets.CreateFunctionPacket
import com.pulse.datapacktools.packets.FunctionCreatedPacket
import net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking
import net.minecraft.server.network.ServerPlayerEntity
import java.io.File

object ServerCreateFunctionPacket {
    fun register() {
        PayloadTypeRegistry.playC2S().register(CreateFunctionPacket.ID, CreateFunctionPacket.CODEC);

        ServerPlayNetworking.registerGlobalReceiver(CreateFunctionPacket.ID) { packet, context ->
            context.server().execute {
                handle(context.player(), packet.functionName)
            }
        }
    }

    fun handle(player: ServerPlayerEntity, functionName: String) {
        val worldDir: File = SessionUtils.worldFolderPath?.toFile() ?: return
        createDefaultDatapack(worldDir)

        val functionsDir = File(worldDir, "datapacks/${ModConfig.data.datapackName}/data/${ModConfig.data.datapackNamespace}/functions")
        val functionDir = File(functionsDir, functionName.substringBeforeLast('/'))
        val functionFile = File(functionsDir, "${functionName}.mcfunction")

        if (functionFile.exists()) return
        if (!functionDir.exists()) functionDir.mkdirs()

        functionFile.writeText("# Generated by DatapackTool")

        ServerPlayNetworking.send(player, FunctionCreatedPacket)

        updateDatapack(player)
    }
}
