package com.pulse.datapacktools.main.packets

import com.pulse.datapacktools.main.config.ModConfig
import com.pulse.datapacktools.main.utils.DatapacksUtils.createDefaultDatapack
import com.pulse.datapacktools.main.utils.DatapacksUtils.updateDatapack
import com.pulse.datapacktools.main.utils.SessionUtils
import net.fabricmc.fabric.api.networking.v1.PacketByteBufs
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking
import net.minecraft.server.network.ServerPlayerEntity
import net.minecraft.util.Identifier
import java.io.File

object CreateFunctionPacket {
    val ID = Identifier("datapacktools", "create_function")
    val ID2 = Identifier("datapacktools", "function_created")

    fun register() {
        ServerPlayNetworking.registerGlobalReceiver(ID) { server, player, handler, buf, responseSender ->
            val functionName = buf.readString()

            if (player.hasPermissionLevel(4)) {
                server.execute {
                    handle(player, functionName)
                }
            }
        }
    }

    fun handle(player: ServerPlayerEntity, functionName: String) {
        val worldDir: File = SessionUtils.worldFolderPath?.toFile() ?: return
        createDefaultDatapack(worldDir)

        val functionsDir = File(worldDir, "datapacks/${ModConfig.data.datapackName}/data/${ModConfig.data.datapackNamespace}/functions")
        val functionDir = File(functionsDir, functionName.substringBeforeLast('/'))
        val functionFile = File(functionsDir, "${functionName}.mcfunction")

        if (functionFile.exists()) return
        if (!functionDir.exists()) functionDir.mkdirs()

        functionFile.writeText("# Generated by DatapackTool")

        ServerPlayNetworking.send(player, ID2, PacketByteBufs.create())

        updateDatapack(player)
    }
}
